script:
  - which fakeroot
  - which svn
  - svn checkout svn://svn.code.sf.net/p/bochs/code/trunk bochs-code
  - find ./ -name configure
  - ./configure && make && make test
  - mkdir page
  - cd page
  - cp -p ../hello* ./
  - git init
  - git config user.name "${USER}"
  - git config user.email "${GHP_MAIL}"
  - echo "<HTML><HEAD><TITLE>LINKS</TITLE></HEAD><BODY><ul>" >index.html
  - for file in $(ls|grep -v index.html); do (printf '<li><a href="' ; printf "${file}" ; printf '">' ; printf "${file}" ; printf '</a></li>\n') >>index.html ; done
  - echo "</ul></BODY></HTML>" >>index.html
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet https://${GHP_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master:gh-pages >/dev/null 2>&1
