os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - bochs-term
    - qemu
script:
  - echo master
  - qemu --help
  - echo
  - find / |grep -i qemu
  - #for i in a b c; do wget -O - https://dugoh.github.io/386bsd0.1/disk.part-a${i}; done|bunzip2 >disk.img
  - #sudo mv disk.img /var/root/
  - #sudo hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount /var/root/disk.img
  - #sudo mkdir /Volumes/m00
  - #sudo mount -t ufs /dev/disk1 /Volumes/m00
  - #sudo find /Volumes/m00
  - #echo
  - #echo ====
  - #echo
  - #sudo diskutil list
  - ./configure && make && make test
  - mkdir page
  - cd page
  - cp -p ../hello* ./
  - git init
  - git config user.name "${USER}"
  - git config user.email "${GHP_MAIL}"
  - echo "<HTML><HEAD><TITLE>LINKS</TITLE></HEAD><BODY><ul>" >index.html
  - for file in $(ls|grep -v index.html); do (printf '<li><a href="' ; printf "${file}" ; printf '">' ; printf "${file}" ; printf '</a></li>\n') >>index.html ; done
  - echo "</ul></BODY></HTML>" >>index.html
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet https://${GHP_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master:gh-pages >/dev/null 2>&1
